export default {
  "kind": "t3",
  "data": {
    "approved_at_utc": null,
    "subreddit": "reactjs",
    "selftext": "&gt; Previous Beginner's Threads can be found in the [wiki][wiki previous threads].\n\nGot questions about React or anything else in its ecosystem?  \nStuck making progress on your app?  \nAsk away! We’re a friendly bunch.\n\nNo question is too simple. 🙂\n\n---\n\n## Want Help with your Code?\n\n1. **Improve your chances** by adding a minimal example with [JSFiddle][jsfiddle], [CodeSandbox][code sandbox], or [Stackblitz][stackblitz].\n    - Describe what you want it to do, and things you've tried. Don't just post big blocks of code!\n    - **[Formatting Code][wiki formatting code]** wiki shows how to format code in this thread.\n1. **Pay it forward!** Answer questions even if there is already an answer. Other perspectives can be helpful to beginners. Also, there's no quicker way to learn than [being wrong on the Internet][being wrong on the internet].\n\n---\n\n## New to React?\n\n### Check out the sub's **sidebar**! 👉\n\n🆓 Here are great, **free** resources!\n\n- [Read the **official** Getting Started page][official getting started page] on the docs.\n- [Microsoft Frontend Bootcamp][microsoft frontend bootcamp]\n- [Codecademy's React courses][codecademy's react courses]\n- [Scrimba's React Course][scrimba's react course]\n- [FreeCodeCamp's React course][freecodecamp's react course]\n- [Kent Dodd's Egghead.io course][kent dodd's egghead.io course]\n- New to Hooks? Check out [Amelia Wattenberger's Thinking in React Hooks][thinking in react hooks]\n- and these React Hook recipes on [useHooks.com][useHooks.com] by [Gabe Ragland](https://twitter.com/gabe_ragland)\n- What other updated resources do you suggest?\n\nAny ideas/suggestions to improve this thread - feel free to comment here!\n\n_Finally, thank you to all who post questions and those who answer them. We're a growing community and [helping each other][learn by teaching] only [strengthens it!][learn in public]_\n\n---\n\n[useHooks.com]: https://usehooks.com/\n[thinking in react hooks]: https://wattenberger.com/blog/react-hooks\n[freecodecamp's react course]: https://www.freecodecamp.org/news/learn-react-course/\n[microsoft frontend bootcamp]: https://www.reddit.com/r/reactjs/comments/auu02f/microsoft_has_open_sourced_their_frontend/\n[official getting started page]: https://reactjs.org/docs/getting-started.html\n[/u/acemarke]: https://www.reddit.com/u/acemarke\n[suggested resources for learning react]: http://blog.isquaredsoftware.com/2017/12/blogged-answers-learn-react/\n[kent dodd's egghead.io course]: http://kcd.im/beginner-react\n[codecademy's react courses]: https://www.codecademy.com/catalog/language/javascript\n[scrimba's react course]: https://scrimba.com/g/glearnreact\n[wiki formatting code]: https://www.reddit.com/r/reactjs/wiki/index#wiki_formatting_code\n[wiki previous threads]: https://www.reddit.com/r/reactjs/wiki/index#wiki_previous_threads\n[code sandbox]: https://codesandbox.io/s/new\n[jsfiddle]: https://jsfiddle.net/Luktwrdm/\n[stackblitz]: https://stackblitz.com/\n[being wrong on the internet]: https://xkcd.com/386/\n[tweet organization]: https://twitter.com/dan_abramov/status/1027245759232651270?lang=en\n[get started with redux]: https://www.reddit.com/r/reactjs/wiki/index#wiki_getting_started_with_redux\n[learn by teaching]: https://en.wikipedia.org/wiki/Learning_by_teaching\n[learn in public]: https://www.swyx.io/writing/learn-in-public/",
    "author_fullname": "t2_1r41bikz",
    "saved": false,
    "mod_reason_title": null,
    "gilded": 0,
    "clicked": false,
    "title": "Beginner's Thread / Easy Questions (September 2020)",
    "link_flair_richtext": [],
    "subreddit_name_prefixed": "r/reactjs",
    "hidden": false,
    "pwls": 6,
    "link_flair_css_class": "link-flair-needs-help",
    "downs": 0,
    "thumbnail_height": null,
    "top_awarded_type": null,
    "hide_score": false,
    "name": "t3_illwv0",
    "quarantine": false,
    "link_flair_text_color": "light",
    "upvote_ratio": 0.93,
    "author_flair_background_color": null,
    "subreddit_type": "public",
    "ups": 12,
    "total_awards_received": 1,
    "media_embed": {},
    "thumbnail_width": null,
    "author_flair_template_id": null,
    "is_original_content": false,
    "user_reports": [],
    "secure_media": null,
    "is_reddit_media_domain": false,
    "is_meta": false,
    "category": null,
    "secure_media_embed": {},
    "link_flair_text": "Needs Help",
    "can_mod_post": false,
    "score": 12,
    "approved_by": null,
    "author_premium": true,
    "thumbnail": "self",
    "edited": false,
    "author_flair_css_class": null,
    "author_flair_richtext": [],
    "gildings": {},
    "content_categories": null,
    "is_self": true,
    "mod_note": null,
    "created": 1599132596,
    "link_flair_type": "text",
    "wls": 6,
    "removed_by_category": null,
    "banned_by": null,
    "author_flair_type": "text",
    "domain": "self.reactjs",
    "allow_live_comments": false,
    "selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;blockquote&gt;\n&lt;p&gt;Previous Beginner&amp;#39;s Threads can be found in the &lt;a href=\"https://www.reddit.com/r/reactjs/wiki/index#wiki_previous_threads\"&gt;wiki&lt;/a&gt;.&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;Got questions about React or anything else in its ecosystem?&lt;br/&gt;\nStuck making progress on your app?&lt;br/&gt;\nAsk away! We’re a friendly bunch.&lt;/p&gt;\n\n&lt;p&gt;No question is too simple. 🙂&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;h2&gt;Want Help with your Code?&lt;/h2&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;strong&gt;Improve your chances&lt;/strong&gt; by adding a minimal example with &lt;a href=\"https://jsfiddle.net/Luktwrdm/\"&gt;JSFiddle&lt;/a&gt;, &lt;a href=\"https://codesandbox.io/s/new\"&gt;CodeSandbox&lt;/a&gt;, or &lt;a href=\"https://stackblitz.com/\"&gt;Stackblitz&lt;/a&gt;.\n\n&lt;ul&gt;\n&lt;li&gt;Describe what you want it to do, and things you&amp;#39;ve tried. Don&amp;#39;t just post big blocks of code!&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;&lt;a href=\"https://www.reddit.com/r/reactjs/wiki/index#wiki_formatting_code\"&gt;Formatting Code&lt;/a&gt;&lt;/strong&gt; wiki shows how to format code in this thread.&lt;/li&gt;\n&lt;/ul&gt;&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;Pay it forward!&lt;/strong&gt; Answer questions even if there is already an answer. Other perspectives can be helpful to beginners. Also, there&amp;#39;s no quicker way to learn than &lt;a href=\"https://xkcd.com/386/\"&gt;being wrong on the Internet&lt;/a&gt;.&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;hr/&gt;\n\n&lt;h2&gt;New to React?&lt;/h2&gt;\n\n&lt;h3&gt;Check out the sub&amp;#39;s &lt;strong&gt;sidebar&lt;/strong&gt;! 👉&lt;/h3&gt;\n\n&lt;p&gt;🆓 Here are great, &lt;strong&gt;free&lt;/strong&gt; resources!&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;a href=\"https://reactjs.org/docs/getting-started.html\"&gt;Read the &lt;strong&gt;official&lt;/strong&gt; Getting Started page&lt;/a&gt; on the docs.&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://www.reddit.com/r/reactjs/comments/auu02f/microsoft_has_open_sourced_their_frontend/\"&gt;Microsoft Frontend Bootcamp&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://www.codecademy.com/catalog/language/javascript\"&gt;Codecademy&amp;#39;s React courses&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://scrimba.com/g/glearnreact\"&gt;Scrimba&amp;#39;s React Course&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://www.freecodecamp.org/news/learn-react-course/\"&gt;FreeCodeCamp&amp;#39;s React course&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"http://kcd.im/beginner-react\"&gt;Kent Dodd&amp;#39;s Egghead.io course&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;New to Hooks? Check out &lt;a href=\"https://wattenberger.com/blog/react-hooks\"&gt;Amelia Wattenberger&amp;#39;s Thinking in React Hooks&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;and these React Hook recipes on &lt;a href=\"https://usehooks.com/\"&gt;useHooks.com&lt;/a&gt; by &lt;a href=\"https://twitter.com/gabe_ragland\"&gt;Gabe Ragland&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;What other updated resources do you suggest?&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;Any ideas/suggestions to improve this thread - feel free to comment here!&lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;Finally, thank you to all who post questions and those who answer them. We&amp;#39;re a growing community and &lt;a href=\"https://en.wikipedia.org/wiki/Learning_by_teaching\"&gt;helping each other&lt;/a&gt; only &lt;a href=\"https://www.swyx.io/writing/learn-in-public/\"&gt;strengthens it!&lt;/a&gt;&lt;/em&gt;&lt;/p&gt;\n\n&lt;hr/&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
    "likes": null,
    "suggested_sort": "new",
    "banned_at_utc": null,
    "view_count": null,
    "archived": false,
    "no_follow": false,
    "is_crosspostable": false,
    "pinned": false,
    "over_18": false,
    "all_awardings": [
      {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": 0,
        "coin_price": 150,
        "id": "award_f44611f1-b89e-46dc-97fe-892280b13b82",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
        "days_of_premium": 0,
        "tiers_by_required_awardings": null,
        "resized_icons": [
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
            "width": 16,
            "height": 16
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
            "width": 32,
            "height": 32
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
            "width": 48,
            "height": 48
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
            "width": 64,
            "height": 64
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
            "width": 128,
            "height": 128
          }
        ],
        "icon_width": 2048,
        "static_icon_width": 2048,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "Thank you stranger. Shows the award.",
        "end_date": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 2048,
        "name": "Helpful",
        "resized_static_icons": [
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
            "width": 16,
            "height": 16
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
            "width": 32,
            "height": 32
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
            "width": 48,
            "height": 48
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
            "width": 64,
            "height": 64
          },
          {
            "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
            "width": 128,
            "height": 128
          }
        ],
        "icon_format": null,
        "icon_height": 2048,
        "penny_price": null,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png"
      }
    ],
    "awarders": [],
    "media_only": false,
    "link_flair_template_id": "c808a3ce-8520-11e8-b3d4-0e03aa55af0c",
    "can_gild": false,
    "spoiler": false,
    "locked": false,
    "author_flair_text": null,
    "treatment_tags": [],
    "visited": false,
    "removed_by": null,
    "num_reports": null,
    "distinguished": "moderator",
    "subreddit_id": "t5_2zldd",
    "mod_reason_by": null,
    "removal_reason": null,
    "link_flair_background_color": "#b8001f",
    "id": "illwv0",
    "is_robot_indexable": true,
    "report_reasons": null,
    "author": "Charles_Stover",
    "discussion_type": null,
    "num_comments": 216,
    "send_replies": true,
    "whitelist_status": "all_ads",
    "contest_mode": false,
    "mod_reports": [],
    "author_patreon_flair": false,
    "author_flair_text_color": null,
    "permalink": "/r/reactjs/comments/illwv0/beginners_thread_easy_questions_september_2020/",
    "parent_whitelist_status": "all_ads",
    "stickied": true,
    "url": "https://www.reddit.com/r/reactjs/comments/illwv0/beginners_thread_easy_questions_september_2020/",
    "subreddit_subscribers": 213924,
    "created_utc": 1599103796,
    "num_crossposts": 0,
    "media": null,
    "is_video": false
  }
}